### ISSUE TITLE
Possilble color palette

### ISSUE THREAD

**Issue by ifdiego** [rsms/sublime-theme#3]
Hey,

I've been using this theme on sublime for sometime and I'm really liking it.
It's so great that I wonder if you have a color palette for the colors?
I would like to try to make a shell/vim version of this, if I may?
But I couldn't get the colors from code.

**Comment by rsms** [comment]
Colors are in the source files. For example https://github.com/rsms/sublime-theme/blob/main/rsms-dark.sublime-color-scheme
